/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shone_androidtest_HelloWorld */

#ifndef _Included_com_shone_androidtest_HelloWorld
#define _Included_com_shone_androidtest_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shone_androidtest_HelloWorld
 * Method:    printJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shone_androidtest_HelloWorld_printJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
